n = input('Digite algo')
t = type(n)
num = n.isnumeric()
alp = n.isalpha()
alnum = n.isalnum()
print('{} é {}'.format(n, t))
print('É número?--{}'.format(num))
print('É letra?--{}'.format(alp))
print('É alfa-numérico?--{}'.format(alnum))
