frase = 'Testando o Manipulamento de Texto'
print(frase)
print(frase[5])
print(frase[5:13])
print(frase[5:24:2])
print(frase[:8])
print(frase[4:])
print(frase[0::2])
print(len(frase))
print(frase.count('o'))
print(frase.count('o',0,18))
print(frase.find('Te'))
print(frase.find('androide'))
print('texto' in frase)
print('Texto' in frase)
print(frase.replace('Texto', 'androide'))
print(frase.upper())
print(frase.lower())
print(frase.capitalize())
print(frase.title())
frase2 = '    Tem espaços inúteis aqui   '
print(frase2.strip())
print(frase2.rstrip())
print(frase2.lstrip())
print(frase.split())
print('-'.join(frase))
frase3 = frase.split()
print('-'.join(frase3))
print(frase.upper().find('TEXTO'))
dividido = frase.split()
print(dividido[0])
print(dividido[0][3])
print(frase.find('Te',5,33))
